baseURL: "https://ameliegodefroidt.github.io" 
title: Amélie Godefroidt
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3

params:
    description: "This website hosts Amélie Godefroidt's research papers, course materials, data, curriculum vitae, and contact information."
    author: Amélie Godefroidt
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications","courses","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Amélie Godefroidt
          subtitle: "I am an Assistant Professor in Conflict Management at the IESEG School of Management, France. My research focuses on public opinion formation during and after episodes of political violence and social contention."
          imageUrl: "picture.jpg"
          imageTitle: Amélie Godefroidt
          imageWidth: 110
          imageHeight: 130
          buttons:
            - name: Publications
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/

    socialIcons:
        - name: Email
          url: mailto:amelie.godefroidt@kuleuven.be
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=9EjHhVUAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ameliegodefroidt
        - name: Twitter
          url: https://x.com/agodefroidt
        - name: Bluesky
          url: https://bsky.app/profile/ameliegodefroidt.bsky.social
        - name: ORCID
          url: https://orcid.org/0000-0002-5010-2860

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Amélie Godefroidt"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
